import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  output: 'static',
  integrations: [
    starlight({
      title: 'Kleegr Developers',
      description: 'Developer documentation for building integrations, automations, and connected workflows with Kleegr CRM.',
      favicon: '/favicon.svg',
      logo: { src: './src/assets/logo.svg', replacesTitle: false },
      customCss: ['./src/styles/custom.css'],
      lastUpdated: false,
      pagination: true,
      social: {},
      sidebar: [
        {
          label: 'Getting Started',
          items: [{ label: 'Introduction', slug: 'getting-started' }],
        },
        {
          label: 'OAuth 2.0',
          collapsed: false,
          items: [
            { label: 'Overview', slug: 'oauth/overview' },
            { label: 'Scopes', slug: 'oauth/scopes' },
            { label: 'Authorization', slug: 'oauth/authorization' },
            { label: 'External Billing', slug: 'oauth/billing' },
            { label: 'External Authentication', slug: 'oauth/externalauthentication' },
            { label: 'Webhook Authentication', slug: 'oauth/webhookauthentication' },
            { label: 'FAQs', slug: 'oauth/faqs' },
          ],
        },
        {
          label: 'API Reference',
          collapsed: false,
          items: [
            { label: 'All APIs', slug: 'api-reference/overview' },
            { label: 'Contacts', slug: 'api-reference/contacts' },
            { label: 'Conversations', slug: 'api-reference/conversations' },
            { label: 'Calendars', slug: 'api-reference/calendars' },
            { label: 'Opportunities', slug: 'api-reference/opportunities' },
            { label: 'Invoices', slug: 'api-reference/invoices' },
            { label: 'Payments', slug: 'api-reference/payments' },
            { label: 'Users', slug: 'api-reference/users' },
            { label: 'Workflows', slug: 'api-reference/workflows' },
            { label: 'Locations/Sub-Accounts', slug: 'api-reference/locations' },
            { label: 'Products', slug: 'api-reference/products' },
            { label: 'Store', slug: 'api-reference/store' },
            { label: 'Emails', slug: 'api-reference/emails' },
            { label: 'LC Email', slug: 'api-reference/email-isv' },
            { label: 'Social Planner', slug: 'api-reference/social-media-posting' },
            { label: 'Blogs', slug: 'api-reference/blogs' },
            { label: 'Funnels', slug: 'api-reference/funnels' },
            { label: 'Courses', slug: 'api-reference/courses' },
            { label: 'Forms', slug: 'api-reference/forms' },
            { label: 'Surveys', slug: 'api-reference/surveys' },
            { label: 'Media Library', slug: 'api-reference/medias' },
            { label: 'Custom Objects', slug: 'api-reference/objects' },
            { label: 'Associations', slug: 'api-reference/associations' },
            { label: 'Custom Fields', slug: 'api-reference/custom-fields' },
            { label: 'Custom Menus', slug: 'api-reference/custom-menus' },
            { label: 'Businesses', slug: 'api-reference/businesses' },
            { label: 'Companies', slug: 'api-reference/companies' },
            { label: 'Trigger Links', slug: 'api-reference/links' },
            { label: 'Snapshots', slug: 'api-reference/snapshots' },
            { label: 'Campaigns', slug: 'api-reference/campaigns' },
            { label: 'Marketplace', slug: 'api-reference/marketplace' },
            { label: 'SaaS', slug: 'api-reference/saas-api' },
            { label: 'Phone System', slug: 'api-reference/phone-system' },
            { label: 'Voice AI', slug: 'api-reference/voice-ai' },
            { label: 'Conversation AI', slug: 'api-reference/conversation-ai' },
            { label: 'Agent Studio', slug: 'api-reference/agent-studio' },
            { label: 'Ad Manager', slug: 'api-reference/ad-manager' },
            { label: 'Affiliate Manager', slug: 'api-reference/affiliate-manager' },
            { label: 'Knowledge Base', slug: 'api-reference/knowledge-base' },
            { label: 'Proposals', slug: 'api-reference/proposals' },
            { label: 'Brand Boards', slug: 'api-reference/brand-boards' },
            { label: 'OAuth Endpoints', slug: 'api-reference/oauth' },
          ],
        },
        {
          label: 'Webhook Events',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'webhooks/overview' },
            { label: 'AppointmentCreate', slug: 'webhooks/appointmentcreate' },
            { label: 'AppointmentDelete', slug: 'webhooks/appointmentdelete' },
            { label: 'AppointmentUpdate', slug: 'webhooks/appointmentupdate' },
            { label: 'AppInstall', slug: 'webhooks/appinstall' },
            { label: 'AppUninstall', slug: 'webhooks/appuninstall' },
            { label: 'CampaignStatusUpdate', slug: 'webhooks/campaignstatusupdate' },
            { label: 'ContactCreate', slug: 'webhooks/contactcreate' },
            { label: 'ContactDelete', slug: 'webhooks/contactdelete' },
            { label: 'ContactDndUpdate', slug: 'webhooks/contactdndupdate' },
            { label: 'ContactTagUpdate', slug: 'webhooks/contacttagupdate' },
            { label: 'ContactUpdate', slug: 'webhooks/contactupdate' },
            { label: 'ConversationUnread', slug: 'webhooks/conversationunreadwebhook' },
            { label: 'InboundMessage', slug: 'webhooks/inboundmessage' },
            { label: 'InvoiceCreate', slug: 'webhooks/invoicecreate' },
            { label: 'InvoiceSent', slug: 'webhooks/invoicesent' },
            { label: 'InvoiceVoid', slug: 'webhooks/invoicevoid' },
            { label: 'InvoicePaid', slug: 'webhooks/invoicepaid' },
            { label: 'InvoicePartiallyPaid', slug: 'webhooks/invoicepartiallypaid' },
            { label: 'InvoiceDelete', slug: 'webhooks/invoicedelete' },
            { label: 'InvoiceUpdate', slug: 'webhooks/invoiceupdate' },
            { label: 'LCEmailStats', slug: 'webhooks/lcemailstats' },
            { label: 'LocationCreate', slug: 'webhooks/locationcreate' },
            { label: 'LocationUpdate', slug: 'webhooks/locationupdate' },
            { label: 'NoteCreate', slug: 'webhooks/notecreate' },
            { label: 'NoteDelete', slug: 'webhooks/notedelete' },
            { label: 'NoteUpdate', slug: 'webhooks/noteupdate' },
            { label: 'OpportunityCreate', slug: 'webhooks/opportunitycreate' },
            { label: 'OpportunityDelete', slug: 'webhooks/opportunitydelete' },
            { label: 'OpportunityUpdate', slug: 'webhooks/opportunityupdate' },
            { label: 'OpportunityStageUpdate', slug: 'webhooks/opportunitystageupdate' },
            { label: 'OpportunityStatusUpdate', slug: 'webhooks/opportunitystatusupdate' },
            { label: 'OpportunityAssignedTo', slug: 'webhooks/opportunityassignedtoupdate' },
            { label: 'OpportunityMonetaryValue', slug: 'webhooks/opportunitymonetaryvalueupdate' },
            { label: 'OrderCreate', slug: 'webhooks/ordercreate' },
            { label: 'OrderStatusUpdate', slug: 'webhooks/orderstatusupdate' },
            { label: 'OutboundMessage', slug: 'webhooks/outboundmessage' },
            { label: 'PlanChange', slug: 'webhooks/planchange' },
            { label: 'PriceCreate', slug: 'webhooks/pricecreate' },
            { label: 'PriceUpdate', slug: 'webhooks/priceupdate' },
            { label: 'PriceDelete', slug: 'webhooks/pricedelete' },
            { label: 'ProductCreate', slug: 'webhooks/productcreate' },
            { label: 'ProductUpdate', slug: 'webhooks/productupdate' },
            { label: 'ProductDelete', slug: 'webhooks/productdelete' },
            { label: 'ProviderOutbound', slug: 'webhooks/provideroutboundmessage' },
            { label: 'RecordCreate', slug: 'webhooks/recordcreate' },
            { label: 'RecordUpdate', slug: 'webhooks/recordupdate' },
            { label: 'RecordDelete', slug: 'webhooks/recorddelete' },
            { label: 'RelationCreate', slug: 'webhooks/relationcreate' },
            { label: 'RelationDelete', slug: 'webhooks/relationdelete' },
            { label: 'ObjectSchemaCreate', slug: 'webhooks/objectschemacreate' },
            { label: 'ObjectSchemaUpdate', slug: 'webhooks/objectschemaupdate' },
            { label: 'AssociationCreate', slug: 'webhooks/associationcreate' },
            { label: 'AssociationUpdate', slug: 'webhooks/associationupdate' },
            { label: 'AssociationDelete', slug: 'webhooks/associationdelete' },
            { label: 'TaskComplete', slug: 'webhooks/taskcomplete' },
            { label: 'TaskCreate', slug: 'webhooks/taskcreate' },
            { label: 'TaskDelete', slug: 'webhooks/taskdelete' },
            { label: 'UserCreate', slug: 'webhooks/usercreate' },
          ],
        },
        {
          label: 'Marketplace Modules',
          collapsed: true,
          items: [
            { label: 'User Context (SSO)', slug: 'marketplace-modules/shared-secret-customjs-custompages' },
            { label: 'Custom JavaScript', slug: 'marketplace-modules/customjs' },
            { label: 'Conversation Providers', slug: 'marketplace-modules/conversationproviders' },
          ],
        },
        {
          label: 'Reference',
          collapsed: true,
          items: [
            { label: 'Country List', slug: 'country-reference/country' },
            { label: 'API Attribution', slug: 'legal/api-attribution' },
          ],
        },
      ],
      components: { Footer: './src/components/Footer.astro' },
    }),
  ],
});
