export const navigation = [
  {
    title: 'Getting Started',
    links: [
      { href: '/', label: 'Introduction' },
      { href: '/oauth/overview', label: 'Authentication' },
    ]
  },
  {
    title: 'OAuth 2.0',
    links: [
      { href: '/oauth/overview', label: 'Overview' },
      { href: '/oauth/authorization', label: 'Authorization' },
      { href: '/oauth/scopes', label: 'Scopes' },
      { href: '/oauth/external-authentication', label: 'External Auth (SSO)' },
      { href: '/oauth/webhook-authentication', label: 'Webhook Auth' },
      { href: '/oauth/billing', label: 'External Billing' },
      { href: '/oauth/faqs', label: 'FAQs' },
    ]
  },
  {
    title: 'API Reference',
    links: [
      { href: '/api-reference', label: 'All APIs' },
      { href: '/api-reference/contacts', label: 'Contacts' },
      { href: '/api-reference/conversations', label: 'Conversations' },
      { href: '/api-reference/calendars', label: 'Calendars' },
      { href: '/api-reference/opportunities', label: 'Opportunities' },
      { href: '/api-reference/invoices', label: 'Invoices' },
      { href: '/api-reference/payments', label: 'Payments' },
      { href: '/api-reference/users', label: 'Users' },
      { href: '/api-reference/workflows', label: 'Workflows' },
      { href: '/api-reference/locations', label: 'Locations' },
      { href: '/api-reference/businesses', label: 'Businesses' },
      { href: '/api-reference/forms', label: 'Forms' },
      { href: '/api-reference/surveys', label: 'Surveys' },
      { href: '/api-reference/products', label: 'Products' },
      { href: '/api-reference/blogs', label: 'Blogs' },
      { href: '/api-reference/funnels', label: 'Funnels' },
      { href: '/api-reference/social-media-posting', label: 'Social Planner' },
      { href: '/api-reference/snapshots', label: 'Snapshots' },
      { href: '/api-reference/medias', label: 'Media Library' },
      { href: '/api-reference/links', label: 'Trigger Links' },
      { href: '/api-reference/emails', label: 'Emails' },
      { href: '/api-reference/marketplace', label: 'Marketplace' },
      { href: '/api-reference/saas-api', label: 'SaaS API' },
      { href: '/api-reference/custom-menus', label: 'Custom Menus' },
      { href: '/api-reference/custom-fields', label: 'Custom Fields' },
      { href: '/api-reference/objects', label: 'Custom Objects' },
      { href: '/api-reference/associations', label: 'Associations' },
      { href: '/api-reference/companies', label: 'Companies' },
      { href: '/api-reference/courses', label: 'Courses' },
      { href: '/api-reference/email-isv', label: 'LC Email' },
      { href: '/api-reference/campaigns', label: 'Campaigns' },
      { href: '/api-reference/oauth', label: 'OAuth API' },
    ]
  },
  {
    title: 'Webhook Events',
    links: [
      { href: '/webhooks', label: 'All Events' },
      { href: '/webhooks/app-install', label: 'AppInstall' },
      { href: '/webhooks/app-uninstall', label: 'AppUninstall' },
      { href: '/webhooks/contact-create', label: 'ContactCreate' },
      { href: '/webhooks/contact-update', label: 'ContactUpdate' },
      { href: '/webhooks/contact-delete', label: 'ContactDelete' },
      { href: '/webhooks/contact-tag-update', label: 'ContactTagUpdate' },
      { href: '/webhooks/contact-dnd-update', label: 'ContactDndUpdate' },
      { href: '/webhooks/inbound-message', label: 'InboundMessage' },
      { href: '/webhooks/outbound-message', label: 'OutboundMessage' },
      { href: '/webhooks/provider-outbound-message', label: 'ProviderOutbound' },
      { href: '/webhooks/appointment-create', label: 'AppointmentCreate' },
      { href: '/webhooks/appointment-update', label: 'AppointmentUpdate' },
      { href: '/webhooks/appointment-delete', label: 'AppointmentDelete' },
      { href: '/webhooks/opportunity-create', label: 'OpportunityCreate' },
      { href: '/webhooks/opportunity-update', label: 'OpportunityUpdate' },
      { href: '/webhooks/opportunity-delete', label: 'OpportunityDelete' },
      { href: '/webhooks/opportunity-stage-update', label: 'OpportunityStageUpdate' },
      { href: '/webhooks/invoice-create', label: 'InvoiceCreate' },
      { href: '/webhooks/invoice-paid', label: 'InvoicePaid' },
      { href: '/webhooks/invoice-sent', label: 'InvoiceSent' },
      { href: '/webhooks/invoice-void', label: 'InvoiceVoid' },
      { href: '/webhooks/order-create', label: 'OrderCreate' },
      { href: '/webhooks/order-status-update', label: 'OrderStatusUpdate' },
      { href: '/webhooks/user-create', label: 'UserCreate' },
      { href: '/webhooks/location-create', label: 'LocationCreate' },
      { href: '/webhooks/location-update', label: 'LocationUpdate' },
      { href: '/webhooks/note-create', label: 'NoteCreate' },
      { href: '/webhooks/task-create', label: 'TaskCreate' },
      { href: '/webhooks/plan-change', label: 'PlanChange' },
      { href: '/webhooks/product-create', label: 'ProductCreate' },
      { href: '/webhooks/invoice-partially-paid', label: 'InvoicePartiallyPaid' },
      { href: '/webhooks/record-create', label: 'RecordCreate' },
      { href: '/webhooks/record-update', label: 'RecordUpdate' },
      { href: '/webhooks/record-delete', label: 'RecordDelete' },
      { href: '/webhooks/association-create', label: 'AssociationCreate' },
      { href: '/webhooks/relation-create', label: 'RelationCreate' },
      { href: '/webhooks/lc-email-stats', label: 'LCEmailStats' },
    ]
  },
  {
    title: 'Marketplace Modules',
    links: [
      { href: '/marketplace/user-context', label: 'User Context' },
      { href: '/marketplace/custom-js', label: 'Custom JavaScript' },
      { href: '/marketplace/conversation-providers', label: 'Conversation Providers' },
    ]
  },
]
